sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.2.3
  - jruby-1.7.23
services:
  - redis
notifications:
  irc:
    - "irc.freenode.net#sensu"
script: "bundle exec rspec . --tag ~sentinel"
